### ISSUE TITLE
URL typo

### ISSUE THREAD

**Issue by kuri8ive** [python/python-docs-ja#16]
[python-docs-ja/tutorial/index.poの44行目](https://github.com/python/python-docs-ja/blob/3.7/tutorial/index.po#L44)にtypoがあります。
`"Python Web サイト(htts://www.python.org) は、 Python "`

以下のような修正が必要です。
`"Python Web サイト(https://www.python.org) は、 Python "`

**Comment by cocoatomo** [comment]
[Contributing](https://github.com/python/python-docs-ja/blob/3.7/.github/CONTRIBUTING.md) にある通り, このレポジトリでは issue を受け付けていません.
issue を close します.
