### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [python/python-docs-ja#19]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by cocoatomo** [comment]
Thank you for informing us.
I removed them.

https://github.com/python/python-docs-ja/commit/58e11648268c58657d539f0061faf0340a527677
https://github.com/python/python-docs-ja/commit/0db0cf5f749b85e4c101b8b080552fb2b414f815
https://github.com/python/python-docs-ja/commit/7a08163423780fe25f18c8a5099281cbe6a2e86c
