### ISSUE TITLE
Probable typo make PDF build fail

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-ja#2]
I got:
```
! Text line contains an invalid character.
l.66796 ...de{subprocess.Popen()}}}} の stream ^^P
                                                  引数など、ファイル記述子つ...
```

while building with xelatex, and found where it come from, it's from library/socket.po:

```
#: ../../library/socket.rst:1072
msgid ""
"On Windows, the file-like object created by :meth:`makefile` cannot be used "
"where a file object with a file descriptor is expected, such as the stream "
"arguments of :meth:`subprocess.Popen`."
msgstr ""
"Windows では、 :meth:`subprocess.Popen` の stream ^P引数など、ファイル記述子つき file "
"オブジェクトが期待されている場所では、 :meth:`makefile` によって作成される file-like オブジェクトは使用できません。"
```

Problem is the ^P right after the word stream. This ^P is the representation emacs makes of the charachter, which is a 0x10, so a `data link escape`.

```
git grep $'\x10' 
library/socket.po:"Windows では、 :meth:`subprocess.Popen` の stream ^P引数など、ファイル記述子つき file "
```

**Comment by JulienPalard** [comment]
Got another one:

    $ git grep $'\x08'
    library/socket.po:"^H高性能の :mod:`os.sendfile` を使用して、ファイルを EOF まで送信し、送信されたバイトの総数を返します。*file* "

It's a `\x08` character (backspace) at the beginning of a sentence.

**Comment by JulienPalard** [comment]
Both are fixed transifex-side, can someone please `tx pull`?

**Comment by methane** [comment]
done

**Comment by JulienPalard** [comment]
Thanks.
