### ISSUE TITLE
Found a bell character

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-ja#3]
On branch 2.7 only:

    $ git grep $'\x07' 
    installing/index.po:msgstr "Python プロジェクトの多くはソースに基いた配布に強く依存しており、インストールプロセスの一環として、^Gエンドユーザ環境でソースから拡張モジュールをコンパイルすることを期待します。"

It's right before `エ`, grep prints it as `^G` for readability.

**Comment by methane** [comment]
fixed.
