### ISSUE TITLE
python 3.11 released

### ISSUE THREAD

**Issue by rffontenelle** [python/python-docs-ja#37]
Now that Python 3.11 beta is available, how about updating Transifex project with this version?

**Comment by rffontenelle** [comment]
@cocoatomo Hey, there. I don't know exactly the method for making releases available, but [3.11.0 beta 5 was released](https://www.python.org/downloads/release/python-3110b5/). If beta is normally your target for translation, it would be nice to update the script to make it available in Transifex

**Comment by rffontenelle** [comment]
[Python 3.11 is released](https://www.python.org/downloads/release/python-3110/)

**Comment by rffontenelle** [comment]
Transifex *python-newest* project is now set with Python 3.11 release. Please apply the proper branch fixes to this Japanese repository.

**Comment by methane** [comment]
fixed in 8dc7bd85e0877487e84ae759f8110e013bf2fc1a.
