### ISSUE TITLE
Enable scheduling of CI workflow update

### ISSUE THREAD

**Issue by rffontenelle** [python/python-docs-ja#39]
I see that the schedule is disabled in the [.github/workflows/update.yml]() workflow, and I would like to suggestion to have it enabled again.

Having a schedule set for running the update translations workflow is important for a couple reason. First one is that any contributions made for this language in Transifex that don't reach this repository won't be available in the generated translated documentation, because (as you may know) the Python infrastructure fetches translations from the language repository, not from Transifex.

Second reason is that this repository runs the command that updates the source strings in Transifex, `tx push --source`. Whenever there is a fix/change in the source documentation, the source strings in Transifex must be updated too; otherwise one might translate to 100%, but the generated translated documentation will still have some English sentences.

**Comment by methane** [comment]
fixed in 7d40e2c34445b51d7e78e7941d11babeabf03640.
